CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n 

CONFIG_ZMK_NON_LIPO_BATTERY_MANAGEMENT=y

# CR1632 の最大電圧（新品）
CONFIG_ZMK_NON_LIPO_MAX_MV=3200

# 使用限界電圧
CONFIG_ZMK_NON_LIPO_MIN_MV=2000

# 低電圧アラート／スリープ閾値
CONFIG_ZMK_NON_LIPO_LOW_MV=2350
# CR1632 は容量が少ないので若干高め

# zmk-battery-center
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
